Fix ignore-hosts-file operation
This fixes the following error:
Global symbol "$ignore_hosts_file" requires explicit package name at /opt/vyatta/sbin/vyatta-dns-forwarding.pl line 77.
Global symbol "$ignore_hosts_file" requires explicit package name at /opt/vyatta/sbin/vyatta-dns-forwarding.pl line 86.
Global symbol "$ignore_hosts_file" requires explicit package name at /opt/vyatta/sbin/vyatta-dns-forwarding.pl line 99.
Execution of /opt/vyatta/sbin/vyatta-dns-forwarding.pl aborted due to compilation errors.